### ISSUE TITLE
로그인 요청 시의 작동 방식

### ISSUE THREAD

**Issue by remonpie1814** [RyuSeohyeong/sorigalpi_be#63]
현재 로그인 페이지 연동 중입니다
수정 요청 몇 가지 말씀 드리겠습니다

1. 존재하지 않는 이메일일 때 HTTP 에러 코드 404 돌려주지 말고 401로 돌려주길 바랍니다.
   - 404는 서버에 해당 페이지, 이미지, 폰트 기타등등 리소스가 존재하지 않을 때입니다. 로그인 실패 시는 401이 적절할 거 같습니다. 
   - 참고: https://surprisecomputer.tistory.com/47
2. 로그인되었을 때 돌려주는 값이 "로그인되었습니다. jwtToken" 입니다. {"message":"로그인되었습니다", token:jwtToken } 과 같은 식으로 주는 게 편합니다. 발급한 토큰을 프론트에서 저장해두어야 하는데, 문자열을 합쳐서 주면 어디부터 어디까지가 토큰인지 알기 어렵습니다.
3. 다른 api도 마찬가지로 JSON 방식으로 수정해주세요.
4. emailVerified 관련한 기능들은 실제로 이메일을 보내야 하는 게 번거로우니 개발단계에선 꺼두거나 무조건 true가 되게 해두는 편이 좋을 것 같습니다.

**Comment by hy20ni** [comment]
1,2,3 코드 수정중입니다.
4 emailVerified 기본값 1로 설정하겠습니다.

**Comment by hy20ni** [comment]
1 >> 존재하지않는 이메일 401로 돌려주는 것으로 변경했습니다.
4 >> emailVerified 기본값 true로 설정되게 변경했습니다.

2,3 >> 진행중입니다.

**Comment by hy20ni** [comment]
3번 완료

**Comment by hy20ni** [comment]
2번 완료
